In [17]:
import numpy as np
x = np.array([[1,2],[2,4]])
print(x.shape)

(2, 2)


In [18]:
n=np.random.randint(2,40,4)
print(list(n))

[18, 19, 19, 23]


In [19]:
a=np.vstack((x,np.array((3,4))))
print(a)


[[1 2]
 [2 4]
 [3 4]]


In [20]:
b=np.hstack((x,np.array((4,5)).reshape(2,1)))
print(b)

[[1 2 4]
 [2 4 5]]
